### ISSUE TITLE
"enabled":"false" doesn't cancel programmable timer

### ISSUE THREAD

**Issue by gregmac** [Legobas/mqtt-timer#1]
Docs state:

>Timers can be disabled by sending a message with the enabled field set to false.
>
> Behavior if a message with enabled=false is received:
>  * Programmable timer will be removed from the scheduler.
>
> If the enabled field is set no other fields will be applied.

However:

* `enabled` seems to be ignored. For example, the following timer triggers:
  ```json
  {
    "id": "timer1",
    "topic": "test/mqtt-timer",
    "message": "this is disabled",
    "start": "5 sec",
    "enabled":"false"
  }
  ```

* Actual way to cancel a timer seems to be to omit `topic` (or set to `null`), or more intuitively just send an empty object with just `id` like:
  ```json
  {"id":"timer1"}
  ```

I'm not sure if this is a code or just documentation issue.

**Comment by Legobas** [comment]
Hi Greg,

You're right, the documentation could be a little bit better about enabling/disabling timers.
The problem is that I changed the field from **enabled** to **enable**.
My motivation for this change was that 'enable' is a command instead of a 'state'.

The message should be like this:
```json
{
  "id": "timer1",
  "enable":"false"
}
```

or to enable again in the case of a configurable timer:

```json
{
  "id": "timer1",
  "enable":"true"
}
```

**Comment by Legobas** [comment]
I updated the readme and the enable field will be validated now.
